name: QA Test

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: string
      runner_label:
        required: false
        default: "runner-qa"
        type: string
      service:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ${{ inputs.runner_label }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install Dependencies
        run: npm ci

      - name: Run QA Test for Service
        run: npm run test:tag @${{ inputs.service }}
